"""add job posting fields to vacancies

Revision ID: 2c483aba170c
Revises: 5a12521856f6
Create Date: 2026-09-05 15:19:44.866702

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c483aba170c'
down_revision: Union[str, Sequence[str], None] = '5a12521856f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('candidate_application')
    op.drop_table('branch')
    op.drop_table('llm_usage_log')
    op.drop_table('vacancy')
    op.drop_table('work_experience')
    op.drop_table('education')
    op.drop_table('meeting')
    op.alter_column('candidate_applications', 'stage',
               existing_type=postgresql.ENUM('NEW', 'SCREENED_BY_BOT', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'HR_VERIFICATION', name='candidatestage'),
               type_=sa.Enum('NEW', 'SCREENED_BY_BOT', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'HR_VERIFICATION', 'BRANCH_INTERVIEW', 'DIRECTOR_INTERVIEW', name='candidatestage', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.add_column('vacancies', sa.Column('reports_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('job_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('work_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('duties_responsibilities', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('required_qualifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('preferred_qualifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('salary_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacancies', sa.Column('benefits', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'benefits')
    op.drop_column('vacancies', 'salary_range')
    op.drop_column('vacancies', 'preferred_qualifications')
    op.drop_column('vacancies', 'required_qualifications')
    op.drop_column('vacancies', 'duties_responsibilities')
    op.drop_column('vacancies', 'work_hours')
    op.drop_column('vacancies', 'job_summary')
    op.drop_column('vacancies', 'reports_to')
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('candidate_applications', 'stage',
               existing_type=sa.Enum('NEW', 'SCREENED_BY_BOT', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'HR_VERIFICATION', 'BRANCH_INTERVIEW', 'DIRECTOR_INTERVIEW', name='candidatestage', native_enum=False),
               type_=postgresql.ENUM('NEW', 'SCREENED_BY_BOT', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'HR_VERIFICATION', name='candidatestage'),
               existing_nullable=False)
    op.create_table('meeting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hr_chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('boss_chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meeting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('meeting_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reminders_sent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_application.id'], name=op.f('meeting_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], name=op.f('meeting_vacancy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_pkey'))
    )
    op.create_table('education',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('field_of_study', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_application.id'], name=op.f('education_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('education_pkey'))
    )
    op.create_table('work_experience',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_application.id'], name=op.f('work_experience_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_experience_pkey'))
    )
    op.create_table('vacancy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_hard_skill_q1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_hard_skill_q2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_soft_skill_q1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_soft_skill_q2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('llm_cost_usd', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hard_skill_q1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hard_skill_q2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('soft_skill_q1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('soft_skill_q2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('vacancy_branch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vacancy_pkey'))
    )
    op.create_table('llm_usage_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', postgresql.ENUM('VACANCY_GEN', 'CV_EVALUATION', name='llmactiontype'), autoincrement=False, nullable=False),
    sa.Column('tokens_input', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tokens_output', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_usage_log_pkey'))
    )
    op.create_table('branch',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('manager_telegram_chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('branch_pkey'))
    )
    op.create_table('candidate_application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pc_skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hard_skill_a1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hard_skill_a2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('soft_skill_a1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('soft_skill_a2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'TALENT_POOL', 'HIRED', name='applicationstatus'), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resume_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extended_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('photo_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_student', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('education_field', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uz_lang_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rus_lang_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('eng_lang_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('computer_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_experience_years', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crm_tools', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expected_salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_car', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('why_you', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_convicted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('where_heard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accept_offer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('objective_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ai_reasoning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pipeline_stage', sa.VARCHAR(length=50), server_default=sa.text("'yangi'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('candidate_application_branch_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('candidate_application_user_id_fkey')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], name=op.f('candidate_application_vacancy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_application_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey1'))
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
