"""add llm_cost_usd to vacancies table

Revision ID: b1c16118a387
Revises: 329816a7bbea
Create Date: 2026-09-09 12:09:03.037016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c16118a387'
down_revision: Union[str, Sequence[str], None] = '329816a7bbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly ensure the column exists in case production missed it
    op.execute(
        "ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS llm_cost_usd DOUBLE PRECISION DEFAULT 0.0 NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE vacancies DROP COLUMN IF EXISTS llm_cost_usd"
    )
    # ### end Alembic commands ###
