"""add_candidate_baseline_questions

Revision ID: edc2033e1a82
Revises: 0003_vacancy_cost
Create Date: 2026-08-28 20:00:49.174697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'edc2033e1a82'
down_revision: Union[str, Sequence[str], None] = '0003_vacancy_cost'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_application', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('extra_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('marital_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('candidate_application', sa.Column('education_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('uz_lang_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('rus_lang_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('eng_lang_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('computer_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('work_experience_years', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('crm_tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('expected_salary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('has_car', sa.Boolean(), nullable=True))
    op.add_column('candidate_application', sa.Column('why_you', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('is_convicted', sa.Boolean(), nullable=True))
    op.add_column('candidate_application', sa.Column('where_heard', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate_application', sa.Column('accept_offer', sa.Boolean(), nullable=True))
    op.alter_column('candidate_application', 'resume_file_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidate_application', 'photo_file_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidate_application', 'ai_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('CANDIDATE', 'HR', 'DIRECTOR', 'EMPLOYEE', name='userrole'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.alter_column('vacancy', 'branch',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'region',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'category',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'generated_hard_skill_q1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancy', 'generated_hard_skill_q2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancy', 'generated_soft_skill_q1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancy', 'generated_soft_skill_q2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancy', 'hard_skill_q1',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'hard_skill_q2',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'soft_skill_q1',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'soft_skill_q2',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vacancy', 'llm_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'llm_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('vacancy', 'soft_skill_q2',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacancy', 'soft_skill_q1',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacancy', 'hard_skill_q2',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacancy', 'hard_skill_q1',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacancy', 'generated_soft_skill_q2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancy', 'generated_soft_skill_q1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancy', 'generated_hard_skill_q2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancy', 'generated_hard_skill_q1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancy', 'category',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacancy', 'region',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vacancy', 'branch',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=False)
    op.alter_column('user', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('CANDIDATE', 'HR', 'DIRECTOR', 'EMPLOYEE', name='userrole'),
               existing_nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidate_application', 'ai_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('candidate_application', 'photo_file_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidate_application', 'resume_file_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('candidate_application', 'accept_offer')
    op.drop_column('candidate_application', 'where_heard')
    op.drop_column('candidate_application', 'is_convicted')
    op.drop_column('candidate_application', 'why_you')
    op.drop_column('candidate_application', 'has_car')
    op.drop_column('candidate_application', 'expected_salary')
    op.drop_column('candidate_application', 'crm_tools')
    op.drop_column('candidate_application', 'work_experience_years')
    op.drop_column('candidate_application', 'computer_level')
    op.drop_column('candidate_application', 'eng_lang_level')
    op.drop_column('candidate_application', 'rus_lang_level')
    op.drop_column('candidate_application', 'uz_lang_level')
    op.drop_column('candidate_application', 'education_field')
    op.drop_column('candidate_application', 'is_student')
    op.drop_column('candidate_application', 'marital_status')
    op.drop_column('candidate_application', 'extra_phone')
    op.drop_column('candidate_application', 'address')
    op.drop_column('candidate_application', 'email')
    # ### end Alembic commands ###
